language: python

python:
  - "3.5.4"

env:
  - DB='database' USER='postgres' PASSWORD='' HOST='localhost' PORT=5432

# command to install dependencies
install: "pip install -r requirements.txt"

before_install:
    - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c 'create database testdb;' -U postgres
  
# command to run tests
script: python accommodations/manage.py test

after_success:
    - coveralls
 