language: python

python:
  - "3.5.4"

env:
  - DB='database' USER='postgres' PASSWORD='' HOST='localhost' PORT=5432

# command to install dependencies
install: "pip install -r requirements.txt"

before_install:
    - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c 'create database testdb;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
# command to run tests
script: 
  - cd accommodations
  - python manage.py test
  - bundle exec rspec

after_success:
    - coveralls
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
 