# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/andela-facilities
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.5
      - image: postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: accommodations_test_db
          POSTGRES_PASSWORD: ""

      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.5-alpine
      #   environment:
      #     POSTGRES_USER: postgres
      #     POSTGRES_DB: accommodations_test_db
      #     POSTGRES_PASSWORD: ""
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv-django
            . venv-django/bin/activate
            pip install -r requirements.txt
            
      - save_cache:
          paths:
            - ./venv-django
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!

      - run:
          name: run tests
          command: |
            . venv-django/bin/activate
            python accommodations/manage.py test
          environment:
            DATABASE_URL: "postgres://postgres@localhost:5432/accommodations_test_db"
      - store_artifacts:
          path: test-reports
          destination: test-reports
