# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_auto_20180116_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomodationoccupant',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='accomodationoccupant',
            old_name='updated_at',
            new_name='date_modified',
        ),
        migrations.RenameField(
            model_name='accomodationroom',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='accomodationroom',
            old_name='updated_at',
            new_name='date_modified',
        ),
        migrations.RenameField(
            model_name='accomodationspace',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='accomodationspace',
            old_name='updated_at',
            new_name='date_modified',
        ),
    ]
