# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_auto_20180116_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodationoccupant',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='space.AccomodationRoom'),
        ),
        migrations.AlterField(
            model_name='accomodationoccupant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accomodationroom',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space', to='space.AccomodationSpace'),
        ),
    ]
